name: Deploy React App to Server

on:
  push:
    branches:
      - anjana

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_API: ${{ secrets.VITE_API }}
          VITE_SDK_API:${{ secrets.VITE_SDK_API }}
        run: |
          npm ci
          npm run build

      - name: Rename dist to loyalty-frontend
        run: mv ./dist ./loyalty-frontend

      - name: Clean Temporary Directory on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            rm -rf ~/deploy-temp
            mkdir ~/deploy-temp

      - name: Copy Files to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ./loyalty-frontend/
          target: ~/deploy-temp/loyalty-frontend/

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S rm -rf /var/www/html/loyalty-frontend
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S mv ~/deploy-temp/loyalty-frontend /var/www/html/
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S rm -rf ~/deploy-temp
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S rm -rf /var/cache/nginx/*
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S systemctl restart nginx